export const PLACEHOLDER_TYPE = 'PLACEHOLDER_TYPE';

// Misc Types
export const SET_LOADING = 'SET_LOADING';

// Auth types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//Build types
export const ADD_BUILD = 'ADD_BUILD';
export const UPDATE_BUILD = 'UPDATE_BUILD';
export const GET_BUILDS = 'GET_BUILDS';
export const DELETE_BUILD = 'DELETE_BUILDS';
export const BUILDS_ERROR = 'BUILDS_ERROR';
export const FAILED_SUBMISSION = 'FAILED_SUBMISSION';
export const GET_USER_BUILD_LIST = 'GET_USER_BUILD_LIST';

// Job Types
export const GET_JOBS = 'GET_JOBS';
export const JOBS_ERROR = 'JOBS_ERROR';
export const DELETE_JOB = 'DELETE_JOB';
export const ADD_JOB = 'ADD_JOB';
export const ACCEPT_JOB = 'ACCEPT_JOB';
export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOBS = 'UPDATE_JOBS';
export const GET_USER_JOB_QUEUE = 'GET_USER_JOB_QUEUE';
export const GET_USER_REQUESTED_JOBS = 'GET_USER_REQUESTED_JOBS';
export const RESET_JOB_STATE = 'RESET_JOB_STATE';
export const SET_SELECTED_JOB_ID = 'SET_SELECTED_JOB_ID';
export const REMOVE_DELETED_BUILD_FROM_JOBS = 'REMOVE_DELETED_BUILD_FROM_JOBS';

// User Type

export const UPDATE_USER = 'UPDATE_USER';

// Admin Type
export const GET_REGISTRATION_REQUESTS = 'GET_REGISTRATION_REQUESTS';
export const GET_ADMIN_ERROR = 'GET_ADMIN_ERROR';
export const GET_ADMIN_NOTIFICATIONS = 'GET_ADMIN_NOTIFICATIONS';
export const ACCEPT_REGISTRATION_REQUEST = 'ACCEPT_REGISTRATION_REQUEST';